config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'categories/show'
  end
  namespace :api do
    get 'genres/show'
  end
  get 'categories/index'
  get 'categories/edit'
  # devise_for :users
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  namespace :api do 
    resources :categories, only: %i(show)
  end
  namespace :api do 
    resources :products, only: [:show]
  end
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  resources :products, only: [:index, :new, :create, :destroy, :edit, :update, :show] do
    resources :comments, only: [:create]
  end
  root 'products#index'
  
  resources :categories, except: [:new, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :product ,optional: true
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    logger.debug("コントローラーでデバッグだよ")
    logger.debug(@category.name)
    
    @products = Product.where(category_id: params[:id])
    logger.debug(@products)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destory]
  def index
    @category = Category.new
    @categories = Category.all
  end
  def create
    @category = Category.new(category_params)
    
    if @category.save
      redirect_to categories_path
    else
      @categories = Category.all
      render 'index'
    end
  end

  def edit
    # @category = Category.find(params[:id]);
  end
  def update
    logger.debug("category_params")
    logger.debug(category_params)
    # @category = Category.find(params[:id]);
    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end
  def destory
    @category.destory
    redirect_to categories_path
  end 
  private 
    def set_category
      @category = Category.find(params[:id])
    end
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/api/categories_helper.rb
module Api::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<div class="container my-5">

    <div class="row">
        <div class="col-md-3"> </div>
        <div class="col-md-6">
            <%= form_with( model: @category, local:true ) do |f| %>
                <%= f.label :name, 'カテゴリー名' ,class: "my-2" %>
                <%= f.text_field :name, class:'form-control my-2' %>
                <%= f.submit '保存', class: 'btn btn-primary btn-block' %>
            <% end %>
        </div>
        <div class="col-xs-3"> </div>
    </div>
</div>

app/views/categories/index.html.erb
<div class="container my-5">
<h2 class="my-4 bd-highlight">カテゴリ管理</h2>
    <div class="row">
        <div class="col-md-3 card">
            <%= form_with( model: @category, local: true )  do |f| %>
            <%= f.label :name, 'カテゴリー名' ,class: "my-2" %>
            <%= f.text_field :name, class:'form-control my-2' %>
            <%= f.submit '追加', :name => nil , class: 'btn btn-primary btn-block' %>
            <% end %>
        </div>
        <div class="col-md-9">
            <table class="table">
                <thead>
                    <tr>
                        <th> カテゴリー名 </th>
                        <th> </th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody> <% @categories.each do |category| %>
                    <tr>
                        <td> <%= category.name %> </td>
                        <td> <%= link_to '編集', edit_category_path(category), class: 'btn-sm btn-primary' %> </td>
                        <td> <%= link_to '削除', category_path(category), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn-sm btn-danger' %>
                        </td>
                    </tr><% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>