config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'categories/show'
  end
  namespace :api do
    get 'genres/show'
  end
  get 'categories/index'
  get 'categories/edit'
  # devise_for :users
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  namespace :api do 
    resources :categories, only: %i(show)
  end
  namespace :api do 
    resources :products, only: [:show]
  end
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  resources :products, only: [:index, :new, :create, :destroy, :edit, :update, :show] do
    resources :comments, only: [:create]
  end
  root 'products#index'
  
  resources :categories, except: [:new, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :pic , presence: true 
    validates :description , presence: true
    belongs_to :category
    has_many :comments
    
    def self.search(search) #ここでのself.はUser.を意味する
        if search
          where(['name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
        else
          all #全て表示。User.は省略
        end
    end
    def self.save(params,upload)
      logger.debug("if文の中に入りました")
      logger.debug(upload)

      name = upload['datafile'].original_filename
      directory = "app/assets/images"
      store_path = "assets/" + name
      # create the file path
      path = File.join(directory, name)
      logger.debug(path)
      # write the file
      File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
      create(name: params[:name], pic: store_path, category_id: params[:category_id], description: params[:description]  )
   end
end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController
    def show
        @product = Product.find(params[:id])
        # render 'show', formats; 'json', handlers: 'jbuilder'
        render 'show', formats: :json, handlers: 'jbuilder'
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!
    def index
        @user = current_user.id
        @categories = Category.all
        @products = Product.search(params[:search])
    end
    def new 
        @product = Product.new 
    end
    def create
        post = Product.save( product_param,params[:upload] )
    end 
    
    
    def edit
        @product = Product.find(params[:id])
    end
    def update
        product = Product.find(params[:id])
        product.update(product_param)
    end
    def destroy
        product = Product.find(params[:id])
        product.destroy
    end
    def show
        @product = Product.find(params[:id])
        @comments = @product.comments
        @comment = Comment.new
    end
    # def product_params
    #     params.require(:product).permit()
    # end
    private 
    def product_param
        params.require(:product).permit(:name, :pic, :description, :category_id)
    end
    
end

app/helpers/api/products_helper.rb
module Api::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/create.html.erb
<h3>投稿完了</h3>
<a href="/products">一覧へ</a>

app/views/products/destory.html.erb
<a href="/products">一覧へ</a>

app/views/products/edit.html.erb
<div class="container">
<div class="row">
    <div class="col-lg-8 mb-4">
        <h3 class="my-3">商品編集</h3>
        <%= @product.category_id %>
        <%= form_with(model: @product, local: true,multipart: true) do |form| %>
        <div class="control-group form-group">
            <div class="controls">
                <label>名前:</label>
                <%= form.text_field :name , placeholder: "名前" ,class: "form-control" %>
                <p class="help-block"></p>
            </div>
        </div>
        <div class="control-group form-group">
            <div class="controls">
                <label>写真のURL:</label>
                <%= file_field 'upload', 'datafile' %></p>

            </div>
        </div>
        <div class="control-group form-group">
            <div class="controls">
                <label>カテゴリ:</label>
                <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: '選択してください' }, class: 'form-control' %>
            </div>
        </div>
        <div class="control-group form-group">
            <div class="controls">
                <label>商品の説明:</label>
                <%= form.text_area :description , placeholder: "商品の説明" ,class: "form-control" %>
            </div>
        </div>
        <div id="success"></div>
        <!-- For success/fail messages -->
        <%= form.submit "投稿" ,class: "btn btn-primary" %>
        <% end %>
    </div>
</div>
</div>

app/views/products/index.html.erb
<div class="container">
  <h1 class="my-4 bd-highlight">Welcome to Modern Business</h1>
  <div class="p-2 bd-highlight">

  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <% @products.each do |product|  %>
        <div class="col-lg-4">
          <div class="card">

            <img class="card-img-top" src="/<%= product.pic %>">

            <div class="card-body">
              <h1 class="card-title"><%= product.name %></h1>
              <p class="card-text"> <span class="badge badge-primary"><%= product.category.name %></span></p>
              <%#　
               link_to "削除", product_path(product.id), class: 'btn btn-danger', method: :delete　
               link_to "編集", edit_product_path(product.id), class: 'btn btn-primary', method: :get 
              %>
              <%= link_to "詳細", product_path(product.id), class: 'btn btn-primary', method: :get %>

            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-4">

      <!-- Search Widget -->
      <div class="card mb-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
          <%= form_tag(products_path, :method => 'get', id: "search_form") do %>
          <div class="input-group">
            <%= text_field_tag :search, params[:search], class: "form-control" %>
            <span class="input-group-append">
              <%= button_tag 'Search', :name => nil ,id: "sbtn" ,class: "btn btn-secondary" %>
            </span>

          </div>
          <% end %>
        </div>
      </div>

      <!-- Categories Widget -->
      <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
              <% @categories.each do |category| %>
                <li>
                  <a href="#">
                    <%= category.name %></a>
                </li>
              <% end %>
                <li>
                  <a href="#">Web Design</a>
                </li>
                <li>
                  <a href="#">HTML</a>
                </li>
                <li>
                  <a href="#">Freebies</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">JavaScript</a>
                </li>
                <li>
                  <a href="#">CSS</a>
                </li>
                <li>
                  <a href="#">Tutorials</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">Side Widget</h5>
        <div class="card-body">
          You can put anything you want inside of these side widgets. They are easy to use, and feature the new
          Bootstrap 4 card containers!
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
<div class="row">
    <div class="col-lg-8 mb-4">
        <h3 class="my-3">商品登録</h3>
        <%= form_with(model: @product, local: true,multipart: true) do |form| %>
        <div class="control-group form-group">
            <div class="controls">
                <label>名前:</label>
                <%= form.text_field :name , placeholder: "名前" ,class: "form-control" %>
                <p class="help-block"></p>
            </div>
        </div>
        <div class="control-group form-group">
            <div class="controls">
                <label>写真のURL:</label>
                <%= file_field 'upload', 'datafile' %></p>

            </div>
        </div>
        <div class="control-group form-group">
            <div class="controls">
                <label>カテゴリ:</label>
                <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: '選択してください' }, class: 'form-control' %>
            </div>
        </div>
        <div class="control-group form-group">
            <div class="controls">
                <label>商品の説明:</label>
                <%= form.text_area :description , placeholder: "商品の説明" ,class: "form-control" %>
            </div>
        </div>
        <div id="success"></div>
        <!-- For success/fail messages -->
        <%= form.submit "投稿" ,class: "btn btn-primary" %>
        <% end %>
    </div>
</div>
</div>

app/views/products/show.html.erb
<div class="container">
    <div class="row my-4">
        <div class="col-lg-6">
            <h2 class="mb-3">
                <%= @product.name %><%= @product.id %></h2>
            <span class="badge badge-primary"><%= @product.category.name %></span>
            <p><%= @product.description %></p>
        </div>
        <div class="col-lg-6">
            <div class="mb-3 d-flex flex-row-reverse">
                <%= link_to "削除", product_path(@product.id), class: 'btn btn-danger', method: :delete　%>
                <%= link_to "編集", edit_product_path(@product.id), class: 'btn btn-primary mr-2 ', method: :get %>
            </div>

            <img class="img-fluid rounded" src="/<%= @product.pic %>" alt="">
        </div>
    </div>
    <div class="row my-4">
        <h2>コメント一覧</h2>
        <table class="table">
            <% @comments.each do |c|  %>
            <tr>
                <td>
                    <a href="/users/<%= c.user_id %>"><%= c.user.email %></a>
                </td>
                <td>
                    <%= c.content %>
                </td>
            </tr>
            <% end  %>
        </table>
        <div class="col-lg-6">
            <%= form_for( [@product,@comment], class: "col-sm-12 ") do |f| %>
            <div class="form-group">
                <label class="my-2">コメント:</label>
                <%= f.text_area :content, class: "form-control", rows: 5 %>
            </div>
            <%= f.submit "コメントする",class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
</div>

app/views/products/update.html.erb
<h3>更新完了</h3>
<a href="/products">一覧へ</a>