config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'categories/show'
  end
  namespace :api do
    get 'genres/show'
  end
  get 'categories/index'
  get 'categories/edit'
  # devise_for :users
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  namespace :api do 
    resources :categories, only: %i(show)
  end
  namespace :api do 
    resources :products, only: [:show]
  end
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  resources :products, only: [:index, :new, :create, :destroy, :edit, :update, :show] do
    resources :comments, only: [:create]
  end
  root 'products#index'
  
  resources :categories, except: [:new, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :product ,optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :pic , presence: true 
    validates :description , presence: true
    belongs_to :category
    has_many :comments
    
    def self.search(search) #ここでのself.はUser.を意味する
        if search
          where(['name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
        else
          all #全て表示。User.は省略
        end
    end
    def self.save(params,upload)
      logger.debug("if文の中に入りました")
      logger.debug(upload)

      name = upload['datafile'].original_filename
      directory = "app/assets/images"
      store_path = "assets/" + name
      # create the file path
      path = File.join(directory, name)
      logger.debug(path)
      # write the file
      File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
      create(name: params[:name], pic: store_path, category_id: params[:category_id], description: params[:description]  )
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :comments
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    logger.debug("コントローラーでデバッグだよ")
    logger.debug(@category.name)
    
    @products = Product.where(category_id: params[:id])
    logger.debug(@products)
  end
end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController
    def show
        @product = Product.find(params[:id])
        # render 'show', formats; 'json', handlers: 'jbuilder'
        render 'show', formats: :json, handlers: 'jbuilder'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
        "/user/#{current_user.id}"
    end
    
    protected

    # 入力フォームからアカウント名情報をDBに保存するために追加
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destory]
  def index
    @category = Category.new
    @categories = Category.all
  end
  def create
    @category = Category.new(category_params)
    
    if @category.save
      redirect_to categories_path
    else
      @categories = Category.all
      render 'index'
    end
  end

  def edit
    # @category = Category.find(params[:id]);
  end
  def update
    logger.debug("category_params")
    logger.debug(category_params)
    # @category = Category.find(params[:id]);
    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end
  def destory
    @category.destory
    redirect_to categories_path
  end 
  private 
    def set_category
      @category = Category.find(params[:id])
    end
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = Comment.new(comment_params)
        @comment.user_id = current_user.id
        @comment.product_id = params["product_id"]
        logger.debug("comment log")
        logger.debug(params)
        logger.debug(current_user.id)
        if @comment.save
            redirect_back(fallback_location: root_path)
        else
            redirect_back(fallback_location: root_path)
        end
        
    end
    private
    def comment_params
        params.require(:comment).permit(:content)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!
    def index
        @user = current_user.id
        @categories = Category.all
        @products = Product.search(params[:search])
    end
    def new 
        @product = Product.new 
    end
    def create
        post = Product.save( product_param,params[:upload] )
    end 
    
    
    def edit
        @product = Product.find(params[:id])
    end
    def update
        product = Product.find(params[:id])
        product.update(product_param)
    end
    def destroy
        product = Product.find(params[:id])
        product.destroy
    end
    def show
        @product = Product.find(params[:id])
        @comments = @product.comments
        @comment = Comment.new
    end
    # def product_params
    #     params.require(:product).permit()
    # end
    private 
    def product_param
        params.require(:product).permit(:name, :pic, :description, :category_id)
    end
    
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/api/categories_helper.rb
module Api::CategoriesHelper
end

app/helpers/api/products_helper.rb
module Api::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Myapp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>


  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'styles' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
  <header class="site-header">
    <div class="site-header__top">
      <div class="wrapper site-header__wrapper top">
        <nav class="nav">
          <button class="nav__toggle" aria-expanded="false" type="button">
            menu
          </button>
          <ul class="nav__wrapper">
            <li class="nav__item"><a href="/products/">プロダクト</a></li>

          </ul>
        </nav>
        <a href="#"></a>
        <% if user_signed_in? %>
        <%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %>
        <% else %>
        <%= link_to "SIGN IN", new_user_session_path, class: 'post' %>
        <% end %>
      </div>
    </div>
    <% if user_signed_in? %>
    <div class="site-header__bottom">
      <div class="wrapper site-header__wrapper bottom">
        <a href="#" class="brand">プロダクト</a>
        <%= link_to '新規投稿', new_product_path, class: 'button' , method: :get %>
      </div>
    </div>
    <% end %>
    <% if controller.controller_name == "products" && controller.action_name == "index" %>
    <div id="carouselExampleIndicators" class="previews">

      <div class="slider" role="listbox">
        <div class="carousel-item active" style="background-image: url('http://placehold.it/1900x1080')">
          <div class="carousel-caption d-none d-md-block">
            <h3>First Slide</h3>
            <p>This is a description for the first slide.</p>
          </div>
        </div>
        <div class="carousel-item" style="background-image: url('http://placehold.it/1900x1080')">
          <div class="carousel-caption d-none d-md-block">
            <h3>Second Slide</h3>
            <p>This is a description for the second slide.</p>
          </div>
        </div>
        <div class="carousel-item" style="background-image: url('http://placehold.it/1900x1080')">
          <div class="carousel-caption d-none d-md-block">
            <h3>Third Slide</h3>
            <p>This is a description for the third slide.</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>


    </div>
    <% end %>

  </header>

  <%= yield %>
  <%= javascript_pack_tag "hello_vue" %>
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>
</body>

</html>